version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  dev:
    build:
      context: ./
      target: dev
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - redis
    restart: always

  prod:
    build:
      context: ./
      target: production
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    command: npm run start
    environment:
      NODE_ENV: production
    depends_on:
      - redis
    restart: always
